# SPDX-License-Identifier: Apache-2.0
"""Export pitch-deck numbers from ``bench/results.json``.

Every row is a value copied verbatim from the JSON with its JSON path. No number is computed,
rounded, or invented; a path that is absent from the JSON is listed as ``NOT RUN``.
"""

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
RESULTS = ROOT / "bench" / "results.json"
DECK = ROOT / "docs" / "deck-numbers.md"

# (label, path). Path segments are dict keys or list indexes.
_ROWS: list[tuple[str, str]] = [
    ("India suite: attacks measured", "suites.india.attacks"),
    ("India suite: benign scenarios", "suites.india.benign"),
    ("India suite: attack success rate, with TRISHUL", "suites.india.with_trishul.asr"),
    ("India suite: benign utility, with TRISHUL", "suites.india.with_trishul.utility"),
    ("India suite: attack success rate, without", "suites.india.without.asr"),
    ("India suite: benign utility, without", "suites.india.without.utility"),
    ("Attacks blocked", "attacks_blocked"),
    ("Attack success rate (headline)", "attack_success_rate"),
    ("Benign utility percent (headline)", "benign_utility"),
    ("Pipeline p99 latency ms (headline)", "p99_latency_ms"),
    ("Latency total p50 ms, ML on", "latency.ml_on.total.p50"),
    ("Latency total p99 ms, ML on", "latency.ml_on.total.p99"),
    ("Latency total p50 ms, ML off", "latency.ml_off.total.p50"),
    ("Latency total p99 ms, ML off", "latency.ml_off.total.p99"),
    ("Ablation rules_only: attack success rate", "ablation.0.asr"),
    ("Ablation rules_only: utility", "ablation.0.utility"),
    ("Ablation rules_classifier: attack success rate", "ablation.1.asr"),
    ("Ablation rules_classifier: utility", "ablation.1.utility"),
    ("Ablation full: attack success rate", "ablation.2.asr"),
    ("Ablation full: utility", "ablation.2.utility"),
    ("AgentDojo banking: status", "suites.agentdojo.status"),
    ("AgentDojo banking: attack success rate, without", "suites.agentdojo.without.asr"),
    ("AgentDojo banking: attack success rate, with TRISHUL", "suites.agentdojo.with_trishul.asr"),
    ("AgentDojo banking: clean utility, without", "suites.agentdojo.without.utility"),
    ("AgentDojo banking: clean utility, with TRISHUL", "suites.agentdojo.with_trishul.utility"),
    ("Voice anti-spoof accuracy (threshold 0.5)", "voice.at_threshold_0_5.accuracy"),
    ("Voice: spoof accepted (FAR)", "voice.at_threshold_0_5.far_spoof_accepted"),
    ("Voice: real flagged (FRR)", "voice.at_threshold_0_5.frr_real_flagged"),
    ("Voice: real clips", "voice.bonafide_clips"),
]

_MISSING = object()


def _lookup(doc: Any, path: str) -> Any:
    cur = doc
    for seg in path.split("."):
        if isinstance(cur, list):
            try:
                cur = cur[int(seg)]
            except (ValueError, IndexError):
                return _MISSING
        elif isinstance(cur, dict) and seg in cur:
            cur = cur[seg]
        else:
            return _MISSING
    return cur


def _jpath(path: str) -> str:
    out = ""
    for seg in path.split("."):
        out += f"[{seg}]" if seg.isdigit() else f".{seg}"
    return "$" + out


def render_deck(results: dict[str, Any]) -> str:
    lines = [
        "# Deck numbers",
        "",
        "Generated by `trishul bench --export-deck` from `bench/results.json`; do not edit.",
        "Each value is copied verbatim from the JSON path in its row.",
        "",
        f"- git_commit: `{results.get('git_commit', 'unknown')}`",
        f"- generated_at: `{results.get('generated_at', 'unknown')}`",
        "",
        "| Metric | Value | JSON path |",
        "|---|---|---|",
    ]
    for label, path in _ROWS:
        v = _lookup(results, path)
        shown = "NOT RUN: absent from results.json" if v is _MISSING else json.dumps(v)
        lines.append(f"| {label} | {shown} | `{_jpath(path)}` |")
    return "\n".join(lines) + "\n"


def export_deck(results_path: Path = RESULTS, out: Path = DECK) -> Path:
    results = json.loads(results_path.read_text(encoding="utf-8"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_deck(results), encoding="utf-8")
    return out
